base/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('login/', views.login_page, name="login"),
    path('registration/', views.registration_page, name="registration"),
    path('logout/', views.logout_page, name='logout'),

    path('', views.home, name="home"),
    path('detail/<int:id>/', views.detail, name="detail"),
    path('my/', views.my, name="my"),
    path('add/', views.add, name="add"),
    path('edit/<int:id>/', views.edit, name="edit"),
    path('delete/<int:id>/', views.delete, name="delete"),
    # Страница продавца
    path('seller/<int:id>/', views.profile_seller, name='seller'),
    # Ссылка, куда отправляются пост запросы з поиском номера телефона
    path('find_numbers/', views.find_number, name='find_number')
]

simkard/urls.py
from django.contrib import admin
from django.urls import path, include 
from django.conf.urls.static import static 
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('base.urls')),
    path('comments/', include('fluent_comments.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_URL)
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_URL)

base/models.py
import re
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils.translation import gettext_lazy as _
# from phone_field import PhoneField
from phonenumber_field.modelfields import PhoneNumberField
from phonenumber_field.phonenumber import PhoneNumber as OrigPhoneNumber

operators = [
	(1, 'activ'),
	(2, 'kcell'),
	(3, 'altel'),
	(4, 'tele2'),
	(5, 'beeline'),
	(6, 'izi'),
]


class PhoneNumber(models.Model):
	operator = models.PositiveSmallIntegerField('Оператор', choices=operators)
	msisdn = PhoneNumberField('Номер телефона', blank=True)
	price = models.IntegerField('Цена')
	cities = [
		(1, 'Алматы'),
		(2, 'Нур-Султан'),
		(3, 'Шымкент'),
		(4, 'Караганда'),
		(5, 'Павлодар'),
		(6, 'Кызылорда'),
		(7, 'Семей'),
		(8, 'Атырау'),
		(9, 'Актобе'),
		(10, 'Актау'),
		(11, 'Уральск'),
		(12, 'Усть-Каменогорск'),
		(13, 'Кокшетау'),
		(14, 'Петропавловск'),
		(15, 'Талдыкорган'),
		(16, 'Жезказган'),
	]

	is_rent = models.BooleanField('Аренда', default=False)

	city = models.PositiveSmallIntegerField('Город', choices=cities)
	description = models.CharField('Описание', max_length=200)
	contact_phone = PhoneNumberField('Контактный телефон', blank=True)
	owner = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='seller', on_delete=models.CASCADE,)
	created = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(auto_now=True)
	active = models.BooleanField(default=False)
	is_top = models.BooleanField('Топ номер', default=False)

	def __str__(self):
		return str(self.msisdn)

	class Meta:
		verbose_name = 'Красивый номер'
		verbose_name_plural = 'Красивые номера' 

	@property
	def css_class(self):
		s = self.get_operator_display()
		return "title__text_%s" % s

	@property
	def price_html(self):
		if self.is_rent:
			return "%d тг/меc" % self.price
		return "%d тг" % self.price

	# Получение ссылки на страницу номера
	def get_absolute_url(self):
		return reverse('detail', args=[self.pk])

	@property
	def msisdn_custom_national(self):
		return self.without_country_code("msisdn")

	@property
	def contact_phone_custom_national(self):
		return self.without_country_code("contact_phone")

	def without_country_code(self, field):
		_field = self.__getattribute__(field)
		if _field and isinstance(_field, OrigPhoneNumber):
			_field = str(_field.national_number)
			return re.sub(r'^(\d{3})(\d{3})(\d{2})(\d{2})$', r'(\1) \2-\3-\4', _field)
		return ''

base/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from .models import *


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']


class PhoneNumberForm(forms.ModelForm):
    class Meta:
        model = PhoneNumber
        fields = ['operator', 'msisdn', 'city', 'contact_phone', "price", 'is_rent', 'description']

    def __init__(self, *args, **kwargs):
        if "user" in kwargs:
            self.user = kwargs.pop('user')
        super(PhoneNumberForm, self).__init__(*args, **kwargs)

    def save(self, commit=True):
        m = super(PhoneNumberForm, self).save(commit=False)
        if hasattr(self, "user"):
            m.owner = self.user
        if commit:
            m.save()
        return m

    def without_country_code(self, field):
        m = super(PhoneNumberForm, self).clean()
        _field = m.get(field)
        if _field and isinstance(_field, OrigPhoneNumber):
            _field = str(_field.national_number)
            return re.sub(r'^(\d{3})(\d{3})(\d{2})(\d{2})$', r'(\1) \2-\3-\4', _field)
        return ''
    # def clean(self):
    #     # run the standard clean method first
    #     cleaned_data = super(PhoneNumberForm, self).clean()
    #     msisdn = cleaned_data.get("msisdn").replace("-", "")[:10]
    #     contact_phone = cleaned_data.get("contact_phone").replace("-", "")[:10]
    #     cleaned_data['msisdn'] = msisdn
    #     cleaned_data['contact_phone'] = contact_phone
    #
    #     return cleaned_data

base/views.py
import re, pprint
from django.shortcuts import render, redirect
from django.http import HttpResponse, JsonResponse
from django.forms import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.views.decorators.csrf import csrf_exempt

from django.contrib.auth import authenticate, login, logout
from django.contrib import messages

from django.contrib.auth.models import User
from django.views.decorators.http import require_POST

from .models import *
from .forms import *
from .filters import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from post_office import mail


def registration_page(request):
	form = CreateUserForm()

	if request.method == 'POST':
		form = CreateUserForm(request.POST)
		if form.is_valid():
			form.save()
			user = form.cleaned_data.get('username')
			messages.success(request, 'Акаунт создан: ' + user)

			return redirect('login')

	context = {'form': form}
	return render(request, 'accounts/registration.html', context)


def login_page(request):
	if request.method == 'POST':
		username = request.POST.get('username')
		password = request.POST.get('password')

		user = authenticate(request, username=username, password=password )

		if user is not None:
			login(request, user)
			return redirect('home')
		else:
			messages.info(request, 'Логин или пароль неверны')

	context = {}
	return render(request, 'accounts/login.html', context)


def logout_page(request):
	if request.user.is_authenticated:
		logout(request)
	return redirect('home')


def home(request):
	context = {}
	operator = request.GET.get('operator', None)
	filters = {}
	is_rent = request.GET.get('is_rent', None)
	if is_rent is not None:
		# Починил фильтр, он у вас не правильно был написан
		if is_rent == '0':
			filters['is_rent'] = False
			context['this_page'] = 'buy'
		elif is_rent == '1':
			filters['is_rent'] = True
			context['this_page'] = 'order'
	prefix = request.GET.get('prefix', None)
	if prefix is not None:
		context['prefix'] = prefix
		prefix = prefix.replace("*", ".")
	else:
		prefix = "..."
	term = request.GET.get('term', None)
	if term is not None:
		context['term'] = term
		term = term.replace("-", "").replace("*", ".")
		if len(term) == 7:
			filters['msisdn__regex'] = r'^%s%s' % (prefix, term)
		else:
			filters['msisdn__regex'] = r'^%s' % prefix
	elif prefix is not None:
		filters['msisdn__regex'] = r'^%s' % prefix
	if operator is not None:
		filters['operator'] = [op.__getitem__(0) for op in operators if operator in op].pop()

	item_list = PhoneNumber.objects.filter(**filters).all().order_by('-created')
	top_items = PhoneNumber.objects.filter(is_top=True).all()
	page_size = 20
	paginator = Paginator(item_list, page_size)
	page = request.GET.get('page', 1)
	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		items = paginator.page(1)
	except EmptyPage:
		items = paginator.page(paginator.num_pages)
	context['items'] = items
	context["top_items"] = top_items
	return render(request, 'base/index.html', context)


def detail(request, id):
	item = PhoneNumber.objects.get(pk=id)

	context = {'item': item}
	return render(request, 'base/detail.html', context)


def my(request):
	context = {}
	user = request.user
	item_list = PhoneNumber.objects.filter(owner__id=user.pk).order_by('-created').all()
	page_size = 20
	paginator = Paginator(item_list, page_size)
	page = request.GET.get('page', 1)
	try:
		items = paginator.page(page)
	except PageNotAnInteger:
		items = paginator.page(1)
	except EmptyPage:
		items = paginator.page(paginator.num_pages)
	context['items'] = items
	return render(request, 'base/my.html', context)


def add(request):
	user = request.user
	if request.method == 'POST':
		# create a form instance and populate it with data from the request:
		form = PhoneNumberForm(request.POST, user=user)
		# check whether it's valid:
		if form.is_valid():
			form.save()
			mail.send(
				[user.email],
				template='add_new_phone',
				context={
					'number': {
						'msisdn': '+7 %s' % form.without_country_code('msisdn')
					}
				},
				priority='now',
			)
			return redirect('/my/')

	# if a GET (or any other method) we'll create a blank form
	else:
		form = PhoneNumberForm(user=user)

	return render(request, 'base/add.html', {'form': form})


def edit(request, id):
	user = request.user
	item = PhoneNumber.objects.get(pk=id, owner=user)
	if request.method == 'POST':
		# create a form instance and populate it with data from the request:
		form = PhoneNumberForm(request.POST, instance=item)
		# check whether it's valid:
		if form.is_valid():
			form.save()
			return redirect('/my/')

	# if a GET (or any other method) we'll create a blank form
	else:
		form = PhoneNumberForm(instance=item)

	return render(request, 'base/edit.html', {'form': form, 'item': item})


def delete(request, id):
	user = request.user
	if request.method == 'POST':
		item = PhoneNumber.objects.filter(pk=id, owner=user).delete()
	return redirect("/my/")


# Обработка страница продавца
def profile_seller(request, id):
	# Получаю профиль продавца через id использовав стандартную модель пользователя
	seller = User.objects.get(id=id)
	numbers = PhoneNumber.objects.filter(owner=seller)
	context = {'seller': seller, 'numbers': numbers}
	return render(request, 'accounts/seller_account.html', context)


# Получение номера телефона
@csrf_exempt
@require_POST   # Обрабатываю только пост запросы
def find_number(request):
	ajax_prefix = request.POST.get('prefix')
	ajax_number = request.POST.get('number')
	ajax_prefix = f'{ajax_prefix}'.replace('*', '\\d').strip()
	ajax_number = f'{ajax_number}'.replace('*', '\\d').strip()
	full_number = f'\\+?7?{ajax_prefix}{ajax_number}'.replace('-', '').strip()

	# Проверка на какой странице находится юзер: Главная, Купить, Аренда.
	# В зависимости от этого фильтровать номера телефонов
	category = request.POST.get('filter')

	if category == 'buy':
		all_numbers = PhoneNumber.objects.filter(is_rent=False).order_by('-created')
	elif category == 'order':
		all_numbers = PhoneNumber.objects.filter(is_rent=True).order_by('-created')
	else:
		all_numbers = PhoneNumber.objects.all().order_by('-created')

	# all_numbers = all_numbers.filter(msisdn__regex=re.compile(full_number))
	reg_full_number = re.compile(full_number)
	find_numbers = []
	for number in all_numbers:
		res_match = reg_full_number.match(str(number.msisdn.national_number))
		# print(res_match)
		if res_match:
			json_number = {
				'operator': number.get_operator_display(),
				'msisdn': number.msisdn_custom_national,
				'price': number.price,
				'is_rent': number.is_rent,
				'link': number.get_absolute_url(),
				'css_class': number.css_class,
			}
			find_numbers.append(json_number)

	return JsonResponse({'find_numbers': find_numbers})

base/templates/base/add.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

    <div class="form_add_number">
        <form method="POST" action="/add/">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-success" type="submit">Добавить</button>
        </form>
    </div>


{% endblock content %}

{% block scripts %}
  <script type="text/javascript" src="{% static 'js/imask.js' %}"></script>
  <script type="text/javascript">
       $(document).ready(function () {
          {#$("input[name=msisdn]").mask("**********", { placeholder: "", autoclear: false});#}
          {#$("input[name=contact_phone]").mask("**********", { placeholder: "", autoclear: false});#}
          $("input[name=msisdn], input[name=contact_phone]").each((i, el) => {
              new IMask(el, {
                  mask: "+{7} (000) 000-00-00",
                  lazy: false,
                  autofix: true,
                  overwrite: true
              });
          });
       });

  </script>
{% endblock  %}

base/templates/base/detail.html
{% extends 'base/main.html' %}
{% load comments static %}
{% block content %}

<div class="purchase-form">

    <div class="purchase-form-top">
        <div class="purchase-logo"><img src="" alt=""></div>
        <div class="purchase-num">
            <p class="numer-pure">+7{{ item.msisdn_custom_national }}</p>
        </div>
    </div>

    <div class="purchase-form-middle">
        <ul>
            <li>Оператор: {{item.get_operator_display}}</li>
            <li>ЦЕНА: {{item.price}} &#8376;</li>
            <li>ИМЯ ПРОДАВЦА: <a href="{% url 'seller' item.owner.id %}">{{item.owner}}</a></li>
            <li>ГОРОД: {{item.get_city_display}}</li>
            <li>КОНТАКТЫ: <a href="tel:{{item.contact_phone}}">+7{{item.contact_phone_custom_national}}</a></li>
            <li>ОПИСАНИЕ: {{item.description|safe}}</li>
        </ul>
    </div>

    <div class="purchase-form-bottom">
        <ul class="two-button">
            <li><a href="tel:{{item.contact_phone}}">Позвонить</a></li>
            <li><a href="">Написать</a></li>
        </ul>
    </div>
</div>


<div class="comment">

    <a href="">Оставить комментарий</a>
</div>
<br>
<br>
<br>
<br>

{#<div class="regbut-pure">#}
{#    <a href="{% url 'registration' %}">Регистрация</a> / <a href="{%url 'login'%}">Вход</a>#}
{#</div>#}

<link rel="stylesheet" type="text/css" href="{% static 'css/ajaxcomments.css' %}" />
<script type="text/javascript" src="{% static 'js/ajaxcomments.js' %}"></script>

{% render_comment_list for item %}
<br>
<br>
{% render_comment_form for item %}

{% endblock content %}

base/templates/base/edit.html
{% extends 'base/main.html' %}
{% load static %}
{% block content %}

    <div class="form_add_number">
        <form method="POST" action="/edit/{{item.pk}}/">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-warning">Изменить</button>
        </form>

        <form method="POST" action="/delete/{{item.pk}}/">
            {% csrf_token %}
            <button class="btn btn-danger">Удалить</button>
        </form>
    </div>

{% endblock content %}

{% block scripts %}
<script type="text/javascript" src="{% static 'js/imask.js' %}"></script>
  <script type="text/javascript">
       $(document).ready(function () {
          {#$("input[name=msisdn]").mask("**********", { placeholder: "", autoclear: false});#}
          {#$("input[name=contact_phone]").mask("**********", { placeholder: "", autoclear: false});#}
          $("input[name=msisdn], input[name=contact_phone]").each((i, el) => {
              new IMask(el, {
                  mask: "+{7} (000) 000-00-00",
                  lazy: false,
                  autofix: true,
                  overwrite: true
              });
          });
       });

  </script>
{% endblock  %}

base/templates/base/footer 2.html
<?php

//echo('ТАК');	
?>

{% load static %}

<div class="footer">
	<div class="footer__inner">
		
		<div class="footer" style="background-image: url({% static 'img/back.png' %}">
		
		<ul>
			<li>Email:<a href="mailto:Simkard@internet.ru" class="footer__email"> simkard@internet.ru</a></li>
			<li>Написать WhatsApp: <a href="https://api.whatsapp.com/send?phone=77071212321&text=%D0%A5%D0%BE%D1%87%D1%83%20%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D1%8C%20%D0%BD%D0%BE%D0%BC%D0%B5%D1%80" class="footer__whatsapp" target="_blank" >+7(776)776-01-01</a></li>
		</ul>


	</div>
</div>

base/templates/base/footer.html
<?php

//echo('ТАК');	
?>

{% load static %}

<div class="footer">
	<div class="footer__inner">
		
		<div class="footer" style="background-image: url("{% static 'img/back.png' %}">
		
		<ul>
			<li>Email:<a href="mailto:Simkard@internet.ru" class="footer__email"> simkard@internet.ru</a></li>
			<li>Написать WhatsApp: <a href="https://api.whatsapp.com/send?phone=77071212321&text=%D0%A5%D0%BE%D1%87%D1%83%20%D0%B7%D0%B0%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D1%8C%20%D0%BD%D0%BE%D0%BC%D0%B5%D1%80" class="footer__whatsapp" target="_blank" >+7(776)776-01-01</a></li>
		</ul>


	</div>
</div>

base/templates/base/header 2.html
<div class="header">
	<div class="header__section">
		<div class="header__item1 headerButton"><a href="{% url 'home' %}" class=" custom-btn btn-2">Главная</a></div>

			<div class="regbut"><a href="{% url 'registration' %}">Регистрация</a> / <a href="{% url 'login' %}"> Вход</a> </div>
	</div>
	
	<div class="header__section">
		<div class="header__item2 "><a href="{% url 'buy' %}" class="custom-btn btn-2">Купить</a></div>
		<div class="header__item2 "><a href="{% url 'lease' %}" class="custom-btn btn-2">Аренда</a></div>
	</div>
</div>

base/templates/base/header.html
<div class="header">
	<div class="header__section">
		<div class="header__item1 headerButton" id="link-home"><a href="{% url 'home' %}" class="btn-2">Главная</a></div>

		<div class="regbut">
			{% if user.is_authenticated %}
			{{user.username}}
			<a href="{% url 'my' %}">Мои номера</a> /
      <a href="{% url 'logout' %}">Выход</a>
			{% else %}
			<a href="{% url 'registration' %}">Регистрация  </a> /
			<a href="{% url 'login' %}"> Вход</a>
			{% endif %}

		</div>
	</div>


	<div class="header__section">
		<div class="header__item2" id="header__item2">
			<ul class="menu">
				<li><a href="{% url 'home' %}?is_rent=0" class="btn-2 {% if this_page == 'buy' %}this_page{% endif %}">Купить</a></li>
				<li><a href="{% url 'home' %}?is_rent=1" class="btn-2 {% if this_page == 'order' %}this_page{% endif %}">Аренда</a></li>
			</ul>


		</div>

	</div>
</div>

base/templates/base/index 2.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
	<meta charset="UTF-8">
	<meta charset="ISO-8859-1">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="X-UA-Compatible" content="ie=edge">
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link href="https://fonts.googleapis.com/css2?family=Coda+Caption:wght@800&display=swap" rel="stylesheet">
	<title>Simkard.kz</title>
</head>
<body>
	<div class="conteiner__block">

		{% include 'base/header.html' %}

		{% include 'base/main-index.html' %}

		{% include 'base/footer.html' %}



	</div>

	<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
	<script src="https://unpkg.com/imask"></script>

	<script type="text/javascript">
		var element = document.getElementById('prefix');
		var maskOptions = {
			mask: '000',
			lazy: false
		}
		var mask = new IMask(element, maskOptions);
	</script>


	<script type="text/javascript">
		var element = document.getElementById('phone');
		var maskOptions = {
			mask: '000-00-00',
			lazy: false
		}
		var mask = new IMask(element, maskOptions);
	</script>






</body>
</html>

base/templates/base/main 2.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Coda+Caption:wght@800&display=swap" rel="stylesheet">
    <title>Simkard.kz</title>
</head>
<body>
    <div class="conteiner__block">

        {% include 'base/header.html' %}

        {% block content %}

        {% endblock content %}

        {% include 'base/footer.html' %}

    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script src="https://unpkg.com/imask"></script>

    <script type="text/javascript">
        var element = document.getElementById('prefix');
        var maskOptions = {
            mask: '000',
            lazy: false
        }
        var mask = new IMask(element, maskOptions);
    </script>


    <script type="text/javascript">
        var element = document.getElementById('phone');
        var maskOptions = {
            mask: '000-00-00',
            lazy: false
        }
        var mask = new IMask(element, maskOptions);
    </script>

</body>
</html>

base/templates/base/main.html
<!DOCTYPE html>
{% load static %}

<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css'%}">
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Coda+Caption:wght@800&display=swap" rel="stylesheet">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/newJS/jquery.min.js' %}"></script>
    <title>Simkard.kz</title>
</head>
<body>
    <div class="conteiner__block">

        {% include 'base/header.html' %}

        {% block content %}

        {% endblock content %}

        {% include 'base/footer.html' %}



    </div>



    <script type="text/javascript" src="{% static 'js/newJS/jquery-ui.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/newJS/jquery.maskedinput-1.2.2.js' %}"></script>

    <script type="text/javascript">

        $("#prefix").mask("***", { placeholder: "*", autoclear: false});
        $("#phone").mask("***-**-**", { placeholder: "*", autoclear: false});
    </script>

    {% block scripts %}
    {% endblock %}

    <script type="text/javascript">

        $(document).ready(function () {

            // Get current page URL
            var url = window.location.href;

            // remove # from URL
            url = url.substring(0, (url.indexOf("#") == -1) ? url.length : url.indexOf("#"));

            // remove parameters from URL
            url = url.substring(0, (url.indexOf("?") == -1) ? url.length : url.indexOf("?"));

            // select file name
            url = url.substr(url.lastIndexOf("/") + 1);

            // If file name not avilable
            if (url == '') {
                url = 'index.html';
            }

            // Loop all menu items
            $('.menu li').each(function () {

                // select href
                var href = $(this).find('a').attr('href');

                // Check filename
                if (url == href) {

                    // Add active class
                    $(this).addClass('active');
                }
            });
        });
    </script>


</body>
</html>

base/templates/base/my.html
{% extends 'base/main.html' %}

{% load static %}
{% load my_tags %}

{% block content %}

<div class="add_number">
    <button type="button" class="btn btn-outline-secondary"><a href="{% url 'add' %}">Добавить номер</a></button>
</div>


<div class="numbers__box2">
    <div class="parent2">
        {% for item in items %}
        <tr>
            <td>
                <div class="title__numbers">
                    <h6 class="{{item.css_class}}">{{item.get_operator_display}}</h6>
                    <div class="seven2">
                        <h4>+7</h4>
                        <div class="topnumbox2">
                            <a href="{%url 'edit' item.pk%}" class="topnum2">{{item.msisdn_custom_national}}</a>
                        </div>
                    </div>
                    <h6 class="title__sell">{{item.price_html}}</h6>
                </div>
            </td>
        </tr>
        {% endfor %}
    </div>
    {% if items.has_other_pages %}
    
        <nav aria-label="Page navigation example">
        <ul class="pagination">
            {% if items.has_previous %}
              <li class="page-item"><a class="page-link" href="?{% param_replace page=items.previous_page_number %}"></a></li>
            {% else %}
              <li class="disabled page-item"><span></span></li>
            {% endif %}
            {% for i in items.paginator.page_range %}
              {% if items.number == i %}
                <li class="page-item active"><a class="page-link"><span>{{ i }} <span class="sr-only">(Текущая)</span></a></li>
              {% else %}
                <li class="page-item"><a class="page-link" href="?{% param_replace page=i %}">{{ i }}</a></li>
              {% endif %}
            {% endfor %}
            {% if users.has_next %}
              <li class="page-item"><a class="page-link" href="?{% param_replace page=items.next_page_number %}"></a></li>
            {% else %}
              <li class="disabled page-item"><span></span></li>
            {% endif %}
      </ul>
  </nav>
{% endif %}
</div>
{% endblock content %}

base/templates/base/profile 2.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Profile Template</h1>

{% endblock content %}

base/templates/base/profile.html
{% extends 'base/main.html' %}

{% block content %}

<h1>Profile Template</h1>

{% endblock content %}